name: Quality Assurance
on: [ pull_request ]
jobs:
  QA:
    strategy:
      matrix:
        php: [ '8.2','8.3','8.4','8.5' ]
        lowest: [ '0', '1' ]

    runs-on: ubuntu-24.04
    steps:

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          # Using phar tools allows to avoid errors while installing lowest/latest dependencies
          tools: phing:3, php-cs-fixer:v3.95.11, psalm:6.16.1, phpunit:11.5.55

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Composer dependencies
        env:
          COMPOSER_PREFER_LOWEST: ${{ matrix.lowest }}
        run: composer update

      - name: Install Composer dependencies and validate
        run: >
          phing -longtargets -logger \\Phing\\Listener\\AnsiColorLogger
          -Dcomposer.flags="--no-dev" composer:install composer:validate

      - name: Psalm
        run: >
          phing -longtargets -logger \\Phing\\Listener\\AnsiColorLogger
          -Dbin.psalm=psalm psalm:run

      - name: php-cs-fixer
        run: >
          phing -longtargets -logger \\Phing\\Listener\\AnsiColorLogger
          -Dbin.cs=php-cs-fixer cs:check

      - name: phpunit
        run: >
          phing -longtargets -logger \\Phing\\Listener\\AnsiColorLogger
          -Dbin.phpunit=phpunit phpunit:check
